// =============================================================
// SafePaw Setup Wizard - Entry Point
// =============================================================
// Single binary that serves:
//   1. REST API for configuration and health checks
//   2. Embedded React UI (built at compile time via go:embed)
//   3. WebSocket endpoint for real-time service status
//
// Design decisions:
//   - go:embed bakes the UI into the binary → one container, no nginx
//   - Separate service from gateway → different failure domains
//   - Admin password generated on first launch → wizard is never open
//   - CSP/CORS locked to localhost → no XSS attack surface
// =============================================================

package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"safepaw/wizard/internal/api"
	"safepaw/wizard/internal/config"
	"safepaw/wizard/internal/costhistory"
	"safepaw/wizard/internal/docker"
	"safepaw/wizard/internal/middleware"
)

func main() {
	// ── Step 1: Load configuration ──
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("[FATAL] Configuration error: %v", err)
	}

	log.Printf("[INFO] SafePaw Setup Wizard starting on :%d", cfg.Port)

	// ── Step 2: Initialize Docker client ──
	dc := docker.New(cfg.DockerHost, "safepaw")

	// ── Step 2b: Initialize cost history persistence (optional) ──
	var costPoller *costhistory.Poller
	if cfg.PostgresHost != "" && cfg.PostgresUser != "" && cfg.PostgresPassword != "" {
		store, err := costhistory.NewStore(costhistory.StoreConfig{
			Host:     cfg.PostgresHost,
			Port:     cfg.PostgresPort,
			User:     cfg.PostgresUser,
			Password: cfg.PostgresPassword,
			DBName:   cfg.PostgresDB,
		})
		if err != nil {
			log.Printf("[WARN] Cost history disabled — Postgres unavailable: %v", err)
		} else {
			envReader := func() (map[string]string, error) {
				return api.ReadEnvFile(cfg.EnvFilePath)
			}
			costPoller = costhistory.NewPoller(costhistory.PollerConfig{
				Store:      store,
				GatewayURL: cfg.GatewayURL,
				EnvReader:  envReader,
				Interval:   5 * time.Minute,
			})
		}
	} else {
		log.Println("[INFO] Cost history disabled (POSTGRES_HOST/USER/PASSWORD not set)")
	}

	// ── Step 3: Initialize API handler ──
	handler, err := api.NewHandler(cfg, dc)
	if err != nil {
		log.Fatalf("[FATAL] Failed to initialize API: %v", err)
	}

	// ── Step 4: Build middleware chain ──
	// Order matters: outermost runs first
	//   SecurityHeaders → CORS → AdminAuth → CSRF → RateLimit → Router
	chain := middleware.SecurityHeaders(
		middleware.CORS(cfg.AllowedOrigins,
			middleware.AdminAuth(handler.SessionValidator(),
				middleware.CSRFProtect(cfg.SecureCookies,
					middleware.RateLimit(60, time.Minute,
						handler.Router(),
					),
				),
			),
		),
	)

	// ── Step 5: Configure HTTP server ──
	srv := &http.Server{
		Addr:           fmt.Sprintf(":%d", cfg.Port),
		Handler:        chain,
		ReadTimeout:    15 * time.Second,
		WriteTimeout:   30 * time.Second,
		IdleTimeout:    60 * time.Second,
		MaxHeaderBytes: 1 << 16, // 64KB — prevent header flooding
	}

	// ── Step 6: Start server in goroutine ──
	errCh := make(chan error, 1)
	go func() {
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			errCh <- err
		}
	}()

	log.Printf("[INFO] Wizard UI available at http://localhost:%d", cfg.Port)
	if cfg.PasswordAutoGenerated {
		log.Printf("[INFO] Auto-generated admin password: %s", cfg.AdminPassword)
		log.Println("[INFO] Set WIZARD_ADMIN_PASSWORD in .env to use a fixed password")
	}

	// ── Step 7: Graceful shutdown ──
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	select {
	case sig := <-quit:
		log.Printf("[INFO] Received %s, shutting down...", sig)
	case err := <-errCh:
		log.Printf("[ERROR] Server error: %v", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	if err := srv.Shutdown(ctx); err != nil {
		log.Printf("[ERROR] Shutdown error: %v", err)
	}

	handler.Close()
	if costPoller != nil {
		costPoller.Stop()
	}
	log.Println("[INFO] Wizard stopped")
}
