package config

import (
	"os"
	"strings"
	"testing"
)

func TestLoad_Defaults(t *testing.T) {
	os.Unsetenv("WIZARD_PORT")
	os.Unsetenv("WIZARD_ADMIN_PASSWORD")
	os.Unsetenv("SECURE_COOKIES")

	cfg, err := Load()
	if err != nil {
		t.Fatalf("Load() failed: %v", err)
	}
	if cfg.Port != 3000 {
		t.Errorf("Port = %d, want 3000", cfg.Port)
	}
	if cfg.AdminPassword == "" {
		t.Error("AdminPassword should be auto-generated")
	}
	if !cfg.PasswordAutoGenerated {
		t.Error("PasswordAutoGenerated should be true when no env var set")
	}
	if cfg.SecureCookies {
		t.Error("SecureCookies should be false by default")
	}
}

func TestLoad_CustomPassword(t *testing.T) {
	os.Setenv("WIZARD_ADMIN_PASSWORD", "my-secure-password")
	defer os.Unsetenv("WIZARD_ADMIN_PASSWORD")

	cfg, err := Load()
	if err != nil {
		t.Fatal(err)
	}
	if cfg.AdminPassword != "my-secure-password" {
		t.Errorf("AdminPassword = %q", cfg.AdminPassword)
	}
	if cfg.PasswordAutoGenerated {
		t.Error("PasswordAutoGenerated should be false when password is provided")
	}
}

func TestLoad_SecureCookies(t *testing.T) {
	os.Setenv("SECURE_COOKIES", "true")
	defer os.Unsetenv("SECURE_COOKIES")

	cfg, err := Load()
	if err != nil {
		t.Fatal(err)
	}
	if !cfg.SecureCookies {
		t.Error("SecureCookies should be true")
	}
}

func TestLoad_CustomPort(t *testing.T) {
	os.Setenv("WIZARD_PORT", "4000")
	defer os.Unsetenv("WIZARD_PORT")

	cfg, err := Load()
	if err != nil {
		t.Fatal(err)
	}
	if cfg.Port != 4000 {
		t.Errorf("Port = %d, want 4000", cfg.Port)
	}
}

func TestGenerateSecurePassword(t *testing.T) {
	p1, err := generateSecurePassword(24)
	if err != nil {
		t.Fatal(err)
	}
	if len(p1) != 48 { // 24 bytes = 48 hex chars
		t.Errorf("password length = %d, want 48", len(p1))
	}

	p2, _ := generateSecurePassword(24)
	if p1 == p2 {
		t.Error("two generated passwords should be different")
	}
}

func TestValidateConfig_PortOutOfRange(t *testing.T) {
	os.Setenv("WIZARD_ADMIN_PASSWORD", "x")
	os.Setenv("WIZARD_PORT", "0")
	defer func() {
		os.Unsetenv("WIZARD_ADMIN_PASSWORD")
		os.Unsetenv("WIZARD_PORT")
	}()
	_, err := Load()
	if err == nil {
		t.Fatal("Load() should fail when WIZARD_PORT=0")
	}
	if !strings.Contains(err.Error(), "1-65535") {
		t.Errorf("error should mention port range, got: %v", err)
	}

	os.Setenv("WIZARD_PORT", "65536")
	_, err = Load()
	if err == nil {
		t.Fatal("Load() should fail when WIZARD_PORT=65536")
	}
	os.Unsetenv("WIZARD_PORT")
}

func TestValidateConfig_InvalidGatewayURL(t *testing.T) {
	os.Setenv("WIZARD_ADMIN_PASSWORD", "x")
	os.Setenv("GATEWAY_URL", "not-a-valid-url")
	defer func() {
		os.Unsetenv("WIZARD_ADMIN_PASSWORD")
		os.Unsetenv("GATEWAY_URL")
	}()
	_, err := Load()
	if err == nil {
		t.Fatal("Load() should fail when GATEWAY_URL is invalid")
	}
	if !strings.Contains(err.Error(), "GATEWAY_URL") {
		t.Errorf("error should mention GATEWAY_URL, got: %v", err)
	}
}
