// =============================================================
// SafePaw Setup Wizard - Configuration
// =============================================================
// All settings come from env vars. On first launch, if no
// WIZARD_ADMIN_PASSWORD is set, we generate a random one and
// print it to stdout (once). This ensures the wizard is never
// accidentally open to the network.
// =============================================================

package config

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"strconv"
)

// Config holds all wizard configuration.
type Config struct {
	// Server
	Port int

	// Security
	AdminPassword         string // Required — auto-generated if not set
	PasswordAutoGenerated bool   // True if password was auto-generated (print to stdout)
	OperatorPassword      string // Optional — when set, enables operator role login
	ViewerPassword        string // Optional — when set, enables viewer role login
	SessionSecret         string // Random server-side HMAC key for session signing (never the admin password)
	TOTPSecret            string // Optional — base32 TOTP secret; when set, login requires password + TOTP code
	AllowedOrigins        []string
	SecureCookies         bool // Set Secure flag on cookies (requires HTTPS)

	// Docker
	DockerHost string // Usually unix:///var/run/docker.sock or npipe:////./pipe/docker_engine

	// Paths
	ComposeFilePath string // Path to the project's docker-compose.yml
	EnvFilePath     string // Path to the .env file

	// Postgres (for cost history persistence)
	PostgresHost     string
	PostgresPort     int
	PostgresUser     string
	PostgresPassword string
	PostgresDB       string

	// Gateway
	GatewayURL string // e.g., http://safepaw-gateway:8080
}

// Load reads configuration from environment variables.
func Load() (*Config, error) {
	cfg := &Config{
		Port:            getEnvInt("WIZARD_PORT", 3000),
		AllowedOrigins:  []string{"http://localhost:3000"},
		SecureCookies:   getEnv("SECURE_COOKIES", "false") == "true",
		DockerHost:      getEnv("DOCKER_HOST", defaultDockerHost()),
		ComposeFilePath: getEnv("COMPOSE_FILE_PATH", "/app/docker-compose.yml"),
		EnvFilePath:     getEnv("ENV_FILE_PATH", "/app/.env"),
		TOTPSecret:      getEnv("WIZARD_TOTP_SECRET", ""),
		PostgresHost:    getEnv("POSTGRES_HOST", ""),
		PostgresPort:    getEnvInt("POSTGRES_PORT", 5432),
		PostgresUser:    getEnv("POSTGRES_USER", ""),
		PostgresPassword: getEnv("POSTGRES_PASSWORD", ""),
		PostgresDB:      getEnv("POSTGRES_DB", ""),
		GatewayURL:      getEnv("GATEWAY_URL", "http://safepaw-gateway:8080"),
	}

	// Admin password: use provided or generate a secure random one
	cfg.AdminPassword = os.Getenv("WIZARD_ADMIN_PASSWORD")
	if cfg.AdminPassword == "" {
		generated, err := generateSecurePassword(24)
		if err != nil {
			return nil, fmt.Errorf("failed to generate admin password: %w", err)
		}
		cfg.AdminPassword = generated
		cfg.PasswordAutoGenerated = true
	}

	// Optional RBAC passwords — when set, users can log in with these for reduced privileges
	cfg.OperatorPassword = os.Getenv("WIZARD_OPERATOR_PASSWORD")
	cfg.ViewerPassword = os.Getenv("WIZARD_VIEWER_PASSWORD")

	// Session signing key: always a random server secret, never the admin password.
	// This prevents offline brute-force of the password from a captured session token.
	sessionSecret, err := generateSecurePassword(32)
	if err != nil {
		return nil, fmt.Errorf("failed to generate session secret: %w", err)
	}
	cfg.SessionSecret = sessionSecret

	return cfg, nil
}

// generateSecurePassword creates a cryptographically random hex string.
func generateSecurePassword(byteLength int) (string, error) {
	b := make([]byte, byteLength)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

func getEnv(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

func getEnvInt(key string, fallback int) int {
	if v := os.Getenv(key); v != "" {
		if parsed, err := strconv.Atoi(v); err == nil {
			return parsed
		}
	}
	return fallback
}

// defaultDockerHost returns the platform-appropriate Docker socket path.
func defaultDockerHost() string {
	if _, err := os.Stat(`\\.\pipe\docker_engine`); err == nil {
		return "npipe:////./pipe/docker_engine"
	}
	return "unix:///var/run/docker.sock"
}
